version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: build
          command: |
            cd src
            ls

            echo 1.0.$CIRCLE_BUILD_NUM >> version
            cat version

            APP_VERSION=$(cat version)
            echo $APP_VERSION

            dotnet restore --packages packages -s https://www.myget.org/F/simple-shop/api/v3/index.json -s https://api.nuget.org/v3/index.json
            dotnet build --no-restore --configuration Release --force -p:Version=${APP_VERSION}
      
      - persist_to_workspace:
          root: .
          paths:
            - src/ApiGateway/bin
            - src/version
            - Dockerfile

  publish_docker:
    docker:
      - image: docker
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ./
      - run: |
          ls
          APP_VERSION=$(cat src/version)
          echo $APP_VERSION

          ls ./src/ApiGateway/bin/Release/netcoreapp2.2
          
          docker login -u $dockeruser -p $dockerpassword
          docker build -t dbonessimplestore/apigateway:latest -t dbonessimplestore/apigateway:$APP_VERSION .
          docker push dbonessimplestore/apigateway

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish_docker:
          context: build-ctx
          requires:
            - build