apiVersion: v1
kind: ConfigMap
metadata:
  namespace: apigateway
  name: serviceconfig
  labels:
    app: simple-shop
    team: platform
data:
  svcconfig: |-
    {
      "logging": {
        "logLevel": {
          "default": "Information"
        },
        "logger": "fluentd"
      },

      "tracing": {
        "jaegerUrl":"jaeger-collector.istio-system"
      }     
    }
  ocelotconfig: |-
    {
      "ReRoutes": [
        {
          "DownstreamPathTemplate": "/{everything}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "basket.basket",
              "Port": 7001
            }
          ],
          "UpstreamPathTemplate": "/basket/{everything}"
        },
        {
          "DownstreamPathTemplate": "/{everything}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "catalog.catalog",
              "Port": 7002
            }
          ],
          "UpstreamPathTemplate": "/catalog/{everything}"
        },
        {
          "DownstreamPathTemplate": "/{everything}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "ordering.ordering",
              "Port": 7003
            }
          ],
          "UpstreamPathTemplate": "/ordering/{everything}"
        },
        {
          "DownstreamPathTemplate": "/{everything}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "warehouse.warehouse",
              "Port": 7004
            }
          ],
          "UpstreamPathTemplate": "/warehouse/{everything}"
        }
      ],
      
      
      "GlobalConfiguration": {
        "BaseUrl": "http://localhost:80",
        "RequestIdKey": "OcRequestId"
      }
    }
