apiVersion: v1
kind: Service
metadata:
  namespace: apigateway
  labels:
    app: simple-shop
    component: apigateway
  name: apigateway
spec:
  ports:
  - port: 80
  selector:
    app: simple-shop
    component: apigateway